import argparse
import os


parser = argparse.ArgumentParser()
parser.add_argument('-t', '--time', type=int,
                    help="Duration of the stress test to run in minute(s).")
parser.add_argument('-exe', '--xtu_exe_path', type=str,
                    help="Path of 'XtuUiLauncher.exe', DEFAULT: 'C:\Program Files\Intel\Intel(R) Extreme Tuning Utility\Client\XtuUiLauncher.exe'")
parser.add_argument('-lp', '--log_path', type=str,
                    help="Path of log generated by the monitor, DEFAULT: 'C:\ProgramData\Intel\Intel Extreme Tuning Utility\Monitor Logs'")
parser.add_argument('-f', '--file')

args = parser.parse_args()